PMIDEA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('buy/', include('buy.urls', namespace='buy')),
    path('preventivemaintenance/', include('preventivemaintenance.urls', namespace='preventivemaintenance')),
    path('', include('home.urls', namespace='home')),
]

buy/urls.py
from django.urls import path

from . import views

app_name = 'buy'

urlpatterns = [
    path('buy/<slug:slug>/', views.buy_device, name='buy_view'),
    path('buy/create_dynamic_buy/<slug:slug>', views.create_buy, name='create_buy'),

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_index, name='home_index'),
    path('category/<slug:slug>/', views.home_index, name='category_filter'),
    path('device/<slug:slug>/', views.device_detail, name='device_detail'),
]

preventivemaintenance/urls.py
from django.urls import path

from . import views

app_name = 'preventivemaintenance'

urlpatterns = [
    path('preventivemaintenance/<slug:slug>/', views.preventivemaintenance_view, name='preventivemaintenance_view'),
]

home/models.py
from django.db import models
from django.template.defaultfilters import slugify  # new
from django.urls import reverse
from accounts.models import User


class FirstLevelCategory(models.Model):
    MEDICAL = 'MD'
    HOSPITAL = 'HOS'
    DENTAL = 'DEN'
    LABORATORY = 'LAB'
    FIRST_LEVEL_CHOICES = [
        (MEDICAL, 'Medical'),
        (HOSPITAL, 'Hospital'),
        (DENTAL, 'Dental'),
        (LABORATORY, 'Laboratory'),
    ]

    first_level = models.CharField(choices=FIRST_LEVEL_CHOICES, max_length=10, default=MEDICAL)
    slug = models.SlugField(unique=True, max_length=50)

    class Meta:
        ordering = ('first_level',)
        verbose_name = 'first level category'
        verbose_name_plural = 'first level categories'

    def __str__(self):
        return self.first_level

    def get_absolute_url(self):
        return reverse('home:category_filter', args=[self.slug])


class SecondLevelCategory(models.Model):
    second_level_name = models.CharField(blank=True, max_length=300)
    second_sub_category = models.ForeignKey(FirstLevelCategory, on_delete=models.CASCADE,
                                            related_name='sscategory',
                                            null=True,
                                            blank=True, )

    class Meta:
        ordering = ('second_level_name','second_sub_category')
        verbose_name = 'second level category'
        verbose_name_plural = 'second level categories'

    def __str__(self):
        return f'{self.second_sub_category} / {self.second_level_name}'


class Device(models.Model):
    status = [
        ('p', 'published'),
        ('d', 'draft'),
        ('w', 'Withdrawn'),


    ]

    first_level_category = models.ForeignKey(FirstLevelCategory, on_delete=models.CASCADE, related_name='dfcategory',
                                             blank=False,
                                             null=True)
    second_level_category = models.ForeignKey(SecondLevelCategory, on_delete=models.CASCADE, related_name='dscategory',
                                              blank=False,
                                              null=True)
    name = models.CharField(max_length=100)
    display_status = models.CharField(choices=status, max_length=1, default='d')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='DUser', null=True, blank=True)
    UMDNS = models.PositiveIntegerField(blank=True, null=True)
    risk_class = models.CharField(max_length=10, blank=True)
    modality = models.CharField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now=True)
    history = models.TextField(blank=True)
    slug = models.SlugField(max_length=15, unique=True)

    class Meta:
        ordering = ('first_level_category', 'second_level_category', 'name')
        get_latest_by = 'created'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:device_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super(Device, self).save(*args, **kwargs)

home/views.py
from django.shortcuts import render, get_object_or_404
from .models import Device, FirstLevelCategory


def home_index(request, slug=None):
    device = Device.objects.all()
    first_levels = FirstLevelCategory.objects.all()
    return render(request, 'home/index_home.html',
                  {'device': device, 'first_levels': first_levels})


def device_detail(request, slug):
    device = get_object_or_404(Device, slug=slug)
    return render(request, 'home/device_detail.html', {'device': device})

home/templates/home/device_detail.html
{% extends 'base.html' %}

{% block content %}

    {{ device.name }}<br />
    {{ device.description }}<br />
    {{ device.first_level_category }}<br />
    {{ device.author }}<br />
    <a href="{% url 'buy:buy_view' device.slug %}"> buy condition</a>
    <a href="{% url 'preventivemaintenance:preventivemaintenance_view' device.slug %}"> preventivemaintenance condition</a>


{% endblock %}

home/templates/home/index_home.html
{% extends 'base.html' %}

{% block content %}

    <h1> very welcome</h1>
    {% for first_level in first_levels %}
        <div class="btn-group">
            <a href="{{ first_level.get_absolute_url }}" class="btn btn-danger">{{ first_level.first_level }}</a>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false"></button>
        </div>

    {% endfor %}
    <br>
    <br/>

    {% for de in device %}
        <div class="btn-group">
            <a href="{{ de.get_absolute_url }}" class="btn btn-danger">{{ de.name }}</a>
            <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false"></button>
        </div>

    {% endfor %}

{% endblock %}